### ISSUE TITLE
Regarding the issue with YouTube-AD-Blocker enabled

### ISSUE THREAD

**Issue by CHIHOLUEN** [iamfugui/YouTube-AD-Blocker#1] opened 2023-09-20 15:18 UTC
Hi, fugui. I've been using YouTube-AD-Blocker without any issues until today when I encountered a problem. After enabling the plugin, the video chapters on the right side of YouTube no longer function properly. Is there a way to fix this? Thanks.

**Comment by iamfugui** [comment] 2023-10-03 11:44
Sorry, I just noticed your question now. This issue was caused by incorrect CSS styles and has been addressed in the latest code update.

**Closed** 2023-10-03 20:31 UTC

**Comment by CHIHOLUEN** [comment] 2023-10-08 07:31
OK, thank you for helping me figure it out. thank you for your time.
